# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-blog',
                'doc_host': 'https://jr-parisa.github.io',
                'git_url': 'https://github.com/jr-parisa/nbdev-blog',
                'lib_path': 'nbdev_blog'},
  'syms': {'nbdev_blog.core': {'nbdev_blog.core.foo': ('core.html#foo', 'nbdev_blog/core.py')}}}
